### ISSUE TITLE
`cd` into plugin's directory and run post-update hook before bundling?

### ISSUE THREAD

**Issue by elianiva** [tani/vim-jetpack#12]
Hi! I'm liking this plugin manager so far. I have some minor issues though.

One of the plugin that I'm using is https://github.com/nvim-telescope/telescope-fzf-native.nvim and it requires me to run `make` to build the plugin binary. There are two minor issues with vim-jetpack:

1. I have to `cd` manually into the plugin directory before running `make` because the post-update hook runs in `stdpath("data") . "/site/jetpack/opt/_"` instead of the plugin directory. I'd be happy if I can run `make` without worrying the plugin directory.
2. The `build` directory which contains the binary doesn't get bundled for the first time. I think this is because post-update hook runs after the bundling step. So I need to run `:JetpackSync` twice; the first one is to clone and build the plugin and the second one is to make jetpack bundles the `build` directory because it wasn't there when it runs for the first time.

Thanks!

**Comment by tani** [comment]
I agree that it is uncomfortable to run a plugin build in a directory that is bundled with other plugins.

JetpackSync will perform the following steps to sync your plugins.

1. Clean up the directory
2. Download plugins
3. Update plugins
4. View plugin update differences
5. Bundle (Optimize) Plugins
6. Running the Build Command for a plugins
 

Now, it is possible to swap 5 and 6 and run the build command in the original directory where the source code of the plugin is stored, and then run 5.

However, my concern is that if I run the build command in the original directory, the artifacts generated by the build will contaminate the directory. In fact, it was reported by another community that git pull failed because the cache of Help tags contaminated the original directory during the build.

This should be eliminated by gitignore, but unfortunately we don't have the power to force developers to do so.

So let me suggest a safe way to solve your problem.

If the do option is set, how about isolate it from the bundle? This will place the plugin in an isolated directory at step 5 and isolate it from the bundle. After that, 6 executes the build command in the isolated directory.

In this way, I think we can avoid each other's concerns. However, there is one point that I am concerned about. In this case, since the directory is not bundled, the runtimepath will increase and the startup time may be slightly slower or unstable. Since there are few plug-ins that require the do command, the runtimepath will not increase significantly, so the effect will be minimal.

**Comment by elianiva** [comment]
I see, thanks for the explanation. I think isolating the plugin when the `do` command is set is fine for my specific case. The plugin is loaded on demand anyway so I don't think it would affect the startup time that much.

However, other users might not like it? Other solution I could think of is provide an option to explicitly exclude the package from the bundle. That way whoever wants to run the `do` command but want it to be bundled can do that, and whoever wants it to get isolated can do that as well.

**Comment by tani** [comment]
Please try https://github.com/tani/vim-jetpack/tree/issue12 branch.
The plugin will be loaded by `jetpack#end()` to avoid on-demend loading.
Thus, It should works as well as the other usual plugins.

**Comment by elianiva** [comment]
Great, it works as expected!

**Comment by tani** [comment]
Thank you for confirming it. Cheers 🍻
