### ISSUE TITLE
[Feature] local plugins support

### ISSUE THREAD

**Issue by younger-1** [tani/vim-jetpack#36]
vim-plug supports use local plugins
```viml
" Unmanaged plugin (manually installed and updated)
Plug '~/my-prototype-plugin'
```

**Comment by tani** [comment]
Thank you for the suggestion. I wont fix this issue because of the following reasons.

- Vim-jetpack merges the directory into one by manual command. Thus, you need to run the command for every local project updates if vim-jetpackag manage the local project. However, this is not friendly.

- You can optionally stop the directory merging by the parameter. Then, `Jetpack` works as well as `Plug` for the lcoal project. However, I do not know the difference between `Plug 'path/to/project' and `set rtp+=path/to/project`.

- You can define `command -nargs=1 JetpackLocal set rtp+=<args>` instead of `Jetpack` if you want.

Please tell me you opinion and reopen this issue. Thanks.

**Comment by younger-1** [comment]
Thanks for your reply. I thought it is a good workaround.

I make a bit change of your suggestion:

```vim
  command -nargs=1 JetpackLocal if isdirectory(<args>) | set rtp^=<args> | endif
    \| if isdirectory(<args>..'/after') | set rtp+=<args>/after | endif
```

**Comment by younger-1** [comment]
May I ask how can I lazy load plugins using events?

**Comment by tani** [comment]
Git can understand `file://` protocol. So, please try to use the following code.

```
Jetpack 'file:///absolute/path/to/git/project', { 'on': [ ... ], 'for': [ ... ]}
```

Then, you can use any option as you want.

**Comment by younger-1** [comment]
Awesome!
