### ISSUE TITLE
How to tell if a plugin exists before loading?

### ISSUE THREAD

**Issue by XeroOl** [tani/vim-jetpack#72]
I have a situation where I want to know if a plugin is installed or not (ie jetpack#tap), except I need to know before jetpack#begin is called.

If I call jetpack#tap before jetpack#begin, it always returns false 

Is this possible to do with Jetpack?

**Comment by tani** [comment]
Hi. The short answer is No.

However, you can do that by the following step

```viml
if isdirectory(expand('~/.vim/pack/jetpack/src/plugin-name'))
\||isdirectory(expand('~/.loca/share/nvim/site/pack/jetpack/src/plugin-name'))
\||isdirectory(expand('~/vimfiles/pack/jetpack/src/plugin-name'))
\||isdirectory(expand('~/Local/AppData/nvim-data/site/pack/jetpack/src/plugin-name'))

"do something

endif
```

Cheers!

**Comment by XeroOl** [comment]
I was afraid this might be the case. Thank you very much, though!

**Comment by tani** [comment]
Thank you for the suggestion.

There are four cases for the pacakge

- declared by `jetpack#add` and installed (and enabled by system)
- declared by `jetpack#add` but not installed
- not declared but installed (and never enabled by system)
- not declared and not installed  (and never enabled by system)

`jetpack#tap` is designed for the first two cases. Because jetpack accidentally return falsy true by third option if we employ your idea. Anyway, thanks :)

**Comment by tani** [comment]
Then, it is possible to call `jetpack#tap` beween `jetpack#add` and `jetpack#end`. Cheers!

**Comment by XeroOl** [comment]
It doesn't seem like jetpack#tap can detect whether or not a plugin is installed for me.

**Comment by XeroOl** [comment]
Nevermind, it's working, my mistake.

**Comment by tani** [comment]
Great. Have a nice hacking!
